In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import datetime

from compute import *

In [12]:
#constants
ProjectName = "2912 East 18th street 5plex"
Description = "5 units :: 3bd1ba house 4 X 2bd1ba apartment"
# assumptions
NumberUnits=5
price     = 1250000
rent      = 1110+1350+1300+1465+1675
Carry     = 0
ltv       = 65
loanRatePer = 3.5
expenseRate = 36
rentPF      = 2200*1+1800*4 +2*1200
# Proforma
expenseRatePF= 32.5
capPF        = 4.5
repairCost   = 25000*5+150000

computeProjectSimple(ProjectName, NumberUnits, price, rent,expenseRate, Carry,ltv, loanRatePer, rentPF,expenseRatePF,capPF,repairCost)

    Project   : 2912 East 18th street 5plex
    Purchase  : $1,250,000
    rent roll : $82,800
    NOI       : $52,992
    Expen Rate: 36%
    Cap Rate  : 4.24%
    DebService:
       amount - $812,500
       rate   - 3.5%
       payment- 43,782$
    DSCR      : 1.21%


    Basis     : $1,525,000
    Cap Rate  : 6.27%
    rent roll : $141,600
    NOI       : $95,580
    Expen Rate: 32.5%
    Price     : $2,124,000 @ cap(4.50%)

In [5]:
dfAct = pd.DataFrame(columns=["Value","Monthly","Annual","%"])

dfAct.loc["Purchase Price","Value"] = price
dfAct.loc["closing cost","%"]       = 1
dfAct.loc["Repair","Value"]         = 5000
dfAct.loc["Reserve","Value"]        = 6000*5
dfAct.loc["Rent Roll","Monthly"] = rent
dfAct.loc["Loan Rate","%"]  = 3.5
dfAct.loc["LTV","%"]        = 75
dfAct.loc["Number Of Units","Value"]=5
simpleExpense = 1
dfAct.loc["Expenses","%"]   =30
dfAct.loc["Util Per Unit","Value"]  =0
dfAct.loc["Insurance","%"]  =0.2
dfAct.loc["Taxes","%"]      = 1.25
dfAct.loc["Vacancy","%"]    = 4
dfAct.loc["Management","%"] = 5
dfAct.loc["Maintenance","%"]= 0.3

In [6]:
#derived from tower

dfact = setMonthlyAndAnnual(dfAct)
if simpleExpense ==1:
    noi=computeNoi(rent=dfAct.loc["Rent Roll","Monthly"],expenseRate=dfAct.loc["Expenses","%"])
    dfAct.loc["NOI","Annual"] = noi
    dfAct.loc["Expenses","Monthly"]=dfAct.loc["Expenses","%"]/100. * dfAct.loc["Rent Roll","Monthly"]
else:
    dfAct.loc["Util","Monthly"] = dfAct.loc["Number Of Units","Value"] * dfAct.loc["Util Per Unit","Value"]
    for c in ["Vacancy","Management"]:
        dfAct.loc[c,"Monthly"] = dfAct.loc[c,"%"]/100.*dfAct.loc["Rent Roll","Monthly"]
        dfAct.loc[c,"Monthly"] = dfAct.loc[c,"%"]/100.*dfAct.loc["Rent Roll","Monthly"]
    for c in ["Maintenance","Taxes","Insurance"]:
        dfAct.loc[c,"Monthly"]= dfAct.loc[c,"%"]/100.*dfAct.loc["Purchase Price","Value"]/12.
    dfAct.loc["Expenses","Monthly"] = sum(dfAct.loc[["Vacancy","Management","Maintenance","Taxes","Insurance","Util"],"Monthly"])
    dfAct.loc["NOI","Monthly"]      = dfAct.loc["Rent Roll","Monthly"] - dfAct.loc["Expenses","Monthly"]
    dfAct.loc["Expense","%"] = dfAct.loc["Expenses","Monthly"]/ dfAct.loc["Rent Roll","Monthly"]
    
dfAct.loc["closing cost","Value"]=dfAct.loc["Purchase Price","Value"] * dfAct.loc["closing cost","%"]/100.
dfAct.loc["Cap","%"] = computeCap(
    rent    =dfAct.loc["Rent Roll","Annual"],
    price   =dfAct.loc["Repair","Value"]+dfAct.loc["Purchase Price","Value"] ,
    expenses=dfAct.loc["Expenses","Annual"])    

# loan payment
pmt =  -1*np.pmt(
    dfAct.loc["Loan Rate","%"]/100/12.,
    360,dfAct.loc["Purchase Price","Value"] *dfAct.loc["LTV","%"]/100)
dfAct.loc["Debt Service","Monthly"] = pmt
dfAct.loc["DSCR","%"] = dfAct.loc["NOI","Monthly"] / dfAct.loc["Debt Service","Monthly"] 
dfact = setMonthlyAndAnnual(dfAct)

dfAct.loc["Cash Flow","Annual"] = (dfAct.loc["NOI","Annual"] - dfAct.loc["Debt Service","Annual"]) 

dfAct.loc["Out Of Pocket","Value"]=\
    dfAct.loc["closing cost","Value"]+\
    dfAct.loc["Repair","Value"]+\
    dfAct.loc["Reserve","Value"]+\
    dfAct.loc["Purchase Price","Value"]*(100-dfAct.loc["LTV","%"])/100.
dfAct.loc["Cash Flow","%"] = dfAct.loc["Cash Flow","Annual"] / dfAct.loc["Out Of Pocket","Value"] * 100
dfact = setMonthlyAndAnnual(dfAct)
dfAct

                   Value  Monthly   Annual        %
Purchase Price   1200000      NaN      NaN      NaN
closing cost       12000      NaN      NaN        1
Repair              5000      NaN      NaN      NaN
Reserve            30000      NaN      NaN      NaN
Rent Roll            NaN     6900    82800      NaN
Loan Rate            NaN      NaN      NaN      3.5
LTV                  NaN      NaN      NaN       75
Number Of Units        5      NaN      NaN      NaN
Expenses             NaN     2070    24840       30
Util Per Unit          0      NaN      NaN      NaN
Insurance            NaN      NaN      NaN      0.2
Taxes                NaN      NaN      NaN     1.25
Vacancy              NaN      NaN      NaN        4
Management           NaN      NaN      NaN        5
Maintenance          NaN      NaN      NaN      0.3
NOI                  NaN     4830    57960      NaN
Cap                  NaN      NaN      NaN      NaN
Debt Service         NaN   4041.4  48496.8      NaN
DSCR                 NaN      NaN      NaN      NaN
Cash Flow            NaN  788.598  9463.17  2.72714
Out Of Pocket     347000      NaN      NaN      NaN

In [7]:
computeCap(
    rent    =dfAct.loc["Rent Roll","Annual"],
    price   =1.3e6,
    expenses=dfAct.loc["Expenses","Annual"])

4.458461538461538

In [ ]:
simpleDepreciation=1
rentIncrease=5        # rent increase
maintenanceIncrease=3 # for all OI
years =datetime.datetime.today().year + np.arange(0,10)
dfPF = pd.DataFrame(columns=years)

updates = {'year':1,"expenseRate":30,"repairCost":450000, "rent":2200*2+1500*2+2000*2}

for year in years:
    if year == years[0]:
        dfPF.loc["Rent Roll",year]    = dfAct.loc["Rent Roll","Annual"]
        dfPF.loc["Expenses", year]    = -1*dfAct.loc["Expenses","Annual"]
    elif year == years[0] +updates["year"]:
        dfPF.loc["Rent Roll",year]    = updates["rent"]*12
        dfPF.loc["Expenses",year]     = -1*dfPF.loc["Rent Roll",year] * updates["expenseRate"]/100.
    else:
        dfPF.loc["Rent Roll",year]    = dfPF.loc["Rent Roll",year-1] *(100+rentIncrease)/100.
        dfPF.loc["Expenses",year]     = dfPF.loc["Expenses",year-1]  *(100+maintenanceIncrease)/100.
        
    dfPF.loc["NOI",year]          = dfPF.loc["Rent Roll",year]+dfPF.loc["Expenses",year]
    dfPF.loc["Debt Service",year] = computePmt(dfAct,year=1)*12
    if simpleDepreciation == 1:
        dfPF.loc["Depreciation",year] = (dfAct.loc["Repair","Value"]+dfAct.loc["Purchase Price","Value"])* -2./3./27.5    
    # Cash Flow NOI minus debt service
    dfPF.loc["Cash Flow",year]    = dfPF.loc["NOI",year] + dfPF.loc["Debt Service",year]
    # Profit=NOI minus interest payment
    dfPF.loc["Profit",year]       = dfPF.loc["NOI",year] + computePmt(dfAct,year=1,ptype=LoanPaymentType.Interest)*12    
    # Pre Tax Profit = profit - minus depreciation
    dfPF.loc["Pre-Tax Profit",year]   = dfPF.loc["Profit",year] + dfPF.loc["Depreciation",year]
    dfPF.loc["Cap Rate",year]         = dfPF.loc["NOI",year]      / dfAct.loc["Purchase Price","Value"]*100
    # cash on cash = profit / out of pocket acquisition
    dfPF.loc["Cash on Cash",year]     = dfPF.loc["Profit",year]/ dfAct.loc["Out Of Pocket","Value"] * 100
    #dfPF.loc["Cash Flow","%"] = dfPF.loc["Cash Flow","Annual"] / dfAct.loc["Out Of Pocket","Value"] * 100
dfPF