In [3]:
import numpy as np
import scipy as sp
import pandas as pd
import datetime

from compute import *

In [3]:
#constants
ProjectName = "3751 Third Ave - 5 plex"

# assumptions
NumberUnits=5
price     = 1850000
rent      = 2500 + 1000 + 1300 + 1200 + 1400
Carry     = 0
ltv       = 70
loanRatePer = 3.5
expenseRate = 35
# Proforma
Description  = "Raise rents minimal renovation, charge for parking"
rentPF       = 2500+1800*3+1400+500
expenseRatePF= 32.5
capPF        = 4
repairCost   = 5000*4+5000
computeProjectSimple(ProjectName, NumberUnits, price, rent,expenseRate, Carry,ltv, loanRatePer, rentPF,expenseRatePF,capPF,repairCost,
                    description=Description)

        Project   : 3751 Third Ave - 5 plex
        Purchase  : $1,850,000
        rent roll : $88,800
        NOI       : $57,720
        Expen Rate: 35%
        Cap Rate  : 3.12%
        DebService:
           amount - $1,295,000
           rate   - 3.5%
           payment- 69,782$
        DSCR      : 0.83%


        Descript  : Raise rents minimal renovation, charge for parking
        Basis     : $1,875,000
        Cap Rate  : 4.23%
        rent roll : $117,600
        NOI       : $79,380
        Expen Rate: 32.5%
        Price     : $1,984,500 @ cap(4.00%)

# construction stage Proposal-Front-4x3

currently a 3600 sqft building, convert 3bd/2ba--> to a 1bd1ba & 2bd1ba
then construct a four story building with an elevator, no parking! each flow will have two studios and one 1bd1ba

units sizes are
15x40 ==> 600
15x40 ==> 600
10x40+10x20 ==>  50

In [2]:
from IPython.display import display, HTML
import plotly
from plotly.graph_objs import graph_objs as go
from plotly.offline import iplot
from ipywidgets import *

In [4]:
newSqft           = 7200
oldBuildCost      = 35+50+100
deck              = 100
concretePedaStool = 100
Elevator          = 100
carryCostRate     = 4
purchasePrice     = 1850000
fig = go.Figure()   
df = pd.DataFrame(columns=["Valuation","BuildCost","TotalCost","Profit","ExpRate","rentRoll","Cap","CostPerSqft"])
idx = 0
for expRate in [33]:#range(30,35+1,5):
    for rent in [1700]:#range(1500,1800+1,100):
        for capPF in np.arange(3,5,.5):        
            for costPerSqft in np.arange(200,300+1,25):
                buildCost = newSqft * costPerSqft +oldBuildCost +deck+concretePedaStool+Elevator
                rentRoll = 18 * rent
                valuation = rentRoll * (100-expRate)/100. * 12 / (capPF/100.)
                totalCost = purchasePrice+buildCost + (purchasePrice+buildCost)*carryCostRate/100.
                #print("${Valuation:,}, ${Cost:,}, ${Profit:,}".format(
                #    Valuation=int(valuation), Cost=int(totalCost),Profit=int(valuation-totalCost)))
                df.loc[idx] = [int(valuation),int(buildCost),int(totalCost),int(valuation-totalCost),expRate,rentRoll,capPF,costPerSqft]
                idx+=1
df

,Valuation,BuildCost,TotalCost,Profit,ExpRate,rentRoll,Cap,CostPerSqft
0,8200800.0,1440485.0,3422104.0,4778695.0,33.0,30600.0,3.0,200.0
1,8200800.0,1620485.0,3609304.0,4591495.0,33.0,30600.0,3.0,225.0
2,8200800.0,1800485.0,3796504.0,4404295.0,33.0,30600.0,3.0,250.0
3,8200800.0,1980485.0,3983704.0,4217095.0,33.0,30600.0,3.0,275.0
4,8200800.0,2160485.0,4170904.0,4029895.0,33.0,30600.0,3.0,300.0
5,7029257.0,1440485.0,3422104.0,3607152.0,33.0,30600.0,3.5,200.0
6,7029257.0,1620485.0,3609304.0,3419952.0,33.0,30600.0,3.5,225.0
7,7029257.0,1800485.0,3796504.0,3232752.0,33.0,30600.0,3.5,250.0
8,7029257.0,1980485.0,3983704.0,3045552.0,33.0,30600.0,3.5,275.0
9,7029257.0,2160485.0,4170904.0,2858352.0,33.0,30600.0,3.5,300.0
10,6150600.0,1440485.0,3422104.0,2728495.0,33.0,30600.0,4.0,200.0
11,6150600.0,1620485.0,3609304.0,2541295.0,33.0,30600.0,4.0,225.0
12,6150600.0,1800485.0,3796504.0,2354095.0,33.0,30600.0,4.0,250.0
13,6150600.0,1980485.0,3983704.0,2166895.0,33.0,30600.0,4.0,275.0
14,6150600.0,2160485.0,4170904.0,1979695.0,33.0,30600.0,4.0,300.0
15,5467200.0,1440485.0,3422104.0,2045095.0,33.0,30600.0,4.5,200.0
16,5467200.0,1620485.0,3609304.0,1857895.0,33.0,30600.0,4.5,225.0
17,5467200.0,1800485.0,3796504.0,1670695.0,33.0,30600.0,4.5,250.0
18,5467200.0,1980485.0,3983704.0,1483495.0,33.0,30600.0,4.5,275.0
19,5467200.0,2160485.0,4170904.0,1296295.0,33.0,30600.0,4.5,300.0